// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: data_service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_data_service_proto protoreflect.FileDescriptor

const file_data_service_proto_rawDesc = "" +
	"\n" +
	"\x12data_service.proto\x12\bprotocol\x1a\n" +
	"data.proto\x1a\rrequest.proto\x1a\x0eresponse.proto2f\n" +
	"\vDataService\x12*\n" +
	"\x03get\x12\x11.protocol.Request\x1a\x0e.protocol.Data\"\x00\x12+\n" +
	"\x03set\x12\x0e.protocol.Data\x1a\x12.protocol.Response\"\x00BT\n" +
	"\x17com.icodesoftware.protoB\x12DataServiceFactoryZ%gameclustering.com/tarantula/protocolb\x06proto3"

var file_data_service_proto_goTypes = []any{
	(*Request)(nil),  // 0: protocol.Request
	(*Data)(nil),     // 1: protocol.Data
	(*Response)(nil), // 2: protocol.Response
}
var file_data_service_proto_depIdxs = []int32{
	0, // 0: protocol.DataService.get:input_type -> protocol.Request
	1, // 1: protocol.DataService.set:input_type -> protocol.Data
	1, // 2: protocol.DataService.get:output_type -> protocol.Data
	2, // 3: protocol.DataService.set:output_type -> protocol.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_service_proto_init() }
func file_data_service_proto_init() {
	if File_data_service_proto != nil {
		return
	}
	file_data_proto_init()
	file_request_proto_init()
	file_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_service_proto_rawDesc), len(file_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_service_proto_goTypes,
		DependencyIndexes: file_data_service_proto_depIdxs,
	}.Build()
	File_data_service_proto = out.File
	file_data_service_proto_goTypes = nil
	file_data_service_proto_depIdxs = nil
}
