name: tarantula-app
services:
  postoffice:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: postoffice
    hostname: postoffice
    image: tarantula.postoffice:${VERSION}
    network_mode: "host"
    volumes:
      - volume_postoffice:/home/tarantula/postoffice
    env_file:
      - .env  
  presence:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: presence
    hostname: presence
    image: tarantula.presence:${VERSION}
    volumes:
      - volume_presence:/home/tarantula/presence
    depends_on:
      - postoffice     
    networks:
      - tarantula-app-net
    env_file:
      - .env 
  asset:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: asset
    hostname: asset
    image: tarantula.asset:${VERSION}
    volumes:
      - volume_asset:/home/tarantula/asset  
    depends_on:
      - postoffice  
    networks:
      - tarantula-app-net
    env_file:
      - .env  
  inventory:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: inventory
    hostname: inventory
    image: tarantula.inventory:${VERSION}
    volumes:
      - volume_inventory:/home/tarantula/inventory  
    depends_on:
      - postoffice  
    networks:
      - tarantula-app-net
    env_file:
      - .env   
                    
  admin:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: admin
    hostname: admin
    image: tarantula.admin:${VERSION}
    volumes:
      - volume_admin:/home/tarantula/admin  
    depends_on:
      - asset
      - inventory
      - presence
    networks:
      - tarantula-app-net
    env_file:
      - .env  
  node:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: node
    hostname: node
    image: tarantula.node:${VERSION}
    ports:
      - "9100:9100"
    networks:
      - tarantula-app-net     
  prometheus:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: prometheus
    hostname: prometheus
    image: tarantula.prometheus:${VERSION}
    volumes:
      - volume_prometheus:/var/tarantula/prometheus
    ports:
      - "9090:9090"
    networks:
      - tarantula-app-net  
  web:
    restart: unless-stopped
    container_name: web
    hostname: web
    image: tarantula.nginx:${VERSION}
    ports:
      - "80:80"
    depends_on:
      - admin
    networks:
      - tarantula-app-net

networks:
  tarantula-app-net:
    external: true
volumes:
  volume_postoffice:
  volume_presence:
  volume_asset:
  volume_inventory:
  volume_admin:
  volume_prometheus:
