// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: data_service.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_data_service_proto protoreflect.FileDescriptor

const file_data_service_proto_rawDesc = "" +
	"\n" +
	"\x12data_service.proto\x12\x04data\x1a\n" +
	"data.proto\x1a\rrequest.proto\x1a\x0eresponse.proto2V\n" +
	"\vDataService\x12\"\n" +
	"\x03get\x12\r.data.Request\x1a\n" +
	".data.Data\"\x00\x12#\n" +
	"\x03set\x12\n" +
	".data.Data\x1a\x0e.data.Response\"\x00BP\n" +
	"\x17com.icodesoftware.protoB\x12DataServiceFactoryZ!gameclustering.com/tarantula/datab\x06proto3"

var file_data_service_proto_goTypes = []any{
	(*Request)(nil),  // 0: data.Request
	(*Data)(nil),     // 1: data.Data
	(*Response)(nil), // 2: data.Response
}
var file_data_service_proto_depIdxs = []int32{
	0, // 0: data.DataService.get:input_type -> data.Request
	1, // 1: data.DataService.set:input_type -> data.Data
	1, // 2: data.DataService.get:output_type -> data.Data
	2, // 3: data.DataService.set:output_type -> data.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_service_proto_init() }
func file_data_service_proto_init() {
	if File_data_service_proto != nil {
		return
	}
	file_data_proto_init()
	file_request_proto_init()
	file_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_service_proto_rawDesc), len(file_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_service_proto_goTypes,
		DependencyIndexes: file_data_service_proto_depIdxs,
	}.Build()
	File_data_service_proto = out.File
	file_data_service_proto_goTypes = nil
	file_data_service_proto_depIdxs = nil
}
