name: tarantula-service
services:
  etcd0:
    image: tarantula.etcd:v1.0
    container_name: etcd0
    hostname: etcd0
    restart: unless-stopped
    ports:
      - "2380:2380"
      - "2379:2379"
    networks:
      - tarantula-service-net      
    volumes:
      - volume_etcd0:/var/tarantula/etcd/data

  sql_db:
    image: postgres:16.2-alpine
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tarantula
    ports:
      - "5432:5432"
    networks:
      - tarantula-service-net      
    volumes:
      - volume_postgres:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
    networks:
      - tarantula-service-net
    volumes:
      - volume_kafka:/var/lib/kafka/data          
networks:
  tarantula-service-net:
    external: true

volumes:
  volume_postgres:
  volume_etcd0:
  volume_kafka:
