name: tarantula-service
services:
  sql_db:
    image: postgres:16.2-alpine
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tarantula
    ports:
      - "5432:5432"
    networks:
      - tarantula-service-net      
    volumes:
      - volume_postgres:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      VAULT_ADDR_ADDRESS: "http:/192.168.1.11:8200"
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h","disable_mlock":"true"}'
      SKIP_SETCAP: true
      SKIP_CHOWN: true
    ports:
      - "8200:8200" 
    volumes:
      - volume_vault:/vault/config
      - volume_vault:/vault/file
    command: server
      
networks:
  tarantula-service-net:
    external: true

volumes:
  volume_postgres:
  volume_vault:
