// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: club_service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClubService_Club_FullMethodName       = "/grpc.ClubService/club"
	ClubService_Register_FullMethodName   = "/grpc.ClubService/register"
	ClubService_Unregister_FullMethodName = "/grpc.ClubService/unregister"
	ClubService_List_FullMethodName       = "/grpc.ClubService/list"
	ClubService_Post_FullMethodName       = "/grpc.ClubService/post"
	ClubService_Flow_FullMethodName       = "/grpc.ClubService/flow"
)

// ClubServiceClient is the client API for ClubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClubServiceClient interface {
	Club(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Club, error)
	Register(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Club, error)
	Unregister(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Club, error)
	// server streaming
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Person], error)
	// client streaming
	Post(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Person, Club], error)
	// server-client streaming
	Flow(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Person, Club], error)
}

type clubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClubServiceClient(cc grpc.ClientConnInterface) ClubServiceClient {
	return &clubServiceClient{cc}
}

func (c *clubServiceClient) Club(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Club, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Club)
	err := c.cc.Invoke(ctx, ClubService_Club_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) Register(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Club, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Club)
	err := c.cc.Invoke(ctx, ClubService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) Unregister(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Club, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Club)
	err := c.cc.Invoke(ctx, ClubService_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubServiceClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Person], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClubService_ServiceDesc.Streams[0], ClubService_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Person]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClubService_ListClient = grpc.ServerStreamingClient[Person]

func (c *clubServiceClient) Post(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Person, Club], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClubService_ServiceDesc.Streams[1], ClubService_Post_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Person, Club]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClubService_PostClient = grpc.ClientStreamingClient[Person, Club]

func (c *clubServiceClient) Flow(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Person, Club], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClubService_ServiceDesc.Streams[2], ClubService_Flow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Person, Club]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClubService_FlowClient = grpc.BidiStreamingClient[Person, Club]

// ClubServiceServer is the server API for ClubService service.
// All implementations must embed UnimplementedClubServiceServer
// for forward compatibility.
type ClubServiceServer interface {
	Club(context.Context, *emptypb.Empty) (*Club, error)
	Register(context.Context, *Person) (*Club, error)
	Unregister(context.Context, *Person) (*Club, error)
	// server streaming
	List(*emptypb.Empty, grpc.ServerStreamingServer[Person]) error
	// client streaming
	Post(grpc.ClientStreamingServer[Person, Club]) error
	// server-client streaming
	Flow(grpc.BidiStreamingServer[Person, Club]) error
	mustEmbedUnimplementedClubServiceServer()
}

// UnimplementedClubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClubServiceServer struct{}

func (UnimplementedClubServiceServer) Club(context.Context, *emptypb.Empty) (*Club, error) {
	return nil, status.Error(codes.Unimplemented, "method Club not implemented")
}
func (UnimplementedClubServiceServer) Register(context.Context, *Person) (*Club, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedClubServiceServer) Unregister(context.Context, *Person) (*Club, error) {
	return nil, status.Error(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedClubServiceServer) List(*emptypb.Empty, grpc.ServerStreamingServer[Person]) error {
	return status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedClubServiceServer) Post(grpc.ClientStreamingServer[Person, Club]) error {
	return status.Error(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedClubServiceServer) Flow(grpc.BidiStreamingServer[Person, Club]) error {
	return status.Error(codes.Unimplemented, "method Flow not implemented")
}
func (UnimplementedClubServiceServer) mustEmbedUnimplementedClubServiceServer() {}
func (UnimplementedClubServiceServer) testEmbeddedByValue()                     {}

// UnsafeClubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClubServiceServer will
// result in compilation errors.
type UnsafeClubServiceServer interface {
	mustEmbedUnimplementedClubServiceServer()
}

func RegisterClubServiceServer(s grpc.ServiceRegistrar, srv ClubServiceServer) {
	// If the following call panics, it indicates UnimplementedClubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClubService_ServiceDesc, srv)
}

func _ClubService_Club_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).Club(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_Club_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).Club(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).Register(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClubService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServiceServer).Unregister(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClubService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClubServiceServer).List(m, &grpc.GenericServerStream[emptypb.Empty, Person]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClubService_ListServer = grpc.ServerStreamingServer[Person]

func _ClubService_Post_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClubServiceServer).Post(&grpc.GenericServerStream[Person, Club]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClubService_PostServer = grpc.ClientStreamingServer[Person, Club]

func _ClubService_Flow_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClubServiceServer).Flow(&grpc.GenericServerStream[Person, Club]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClubService_FlowServer = grpc.BidiStreamingServer[Person, Club]

// ClubService_ServiceDesc is the grpc.ServiceDesc for ClubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ClubService",
	HandlerType: (*ClubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "club",
			Handler:    _ClubService_Club_Handler,
		},
		{
			MethodName: "register",
			Handler:    _ClubService_Register_Handler,
		},
		{
			MethodName: "unregister",
			Handler:    _ClubService_Unregister_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "list",
			Handler:       _ClubService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "post",
			Handler:       _ClubService_Post_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "flow",
			Handler:       _ClubService_Flow_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "club_service.proto",
}
