// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: club_service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_club_service_proto protoreflect.FileDescriptor

const file_club_service_proto_rawDesc = "" +
	"\n" +
	"\x12club_service.proto\x12\x04grpc\x1a\fperson.proto\x1a\n" +
	"club.proto\x1a\x1bgoogle/protobuf/empty.proto2\x8d\x02\n" +
	"\vClubService\x12,\n" +
	"\x04club\x12\x16.google.protobuf.Empty\x1a\n" +
	".grpc.Club\"\x00\x12&\n" +
	"\bregister\x12\f.grpc.Person\x1a\n" +
	".grpc.Club\"\x00\x12(\n" +
	"\n" +
	"unregister\x12\f.grpc.Person\x1a\n" +
	".grpc.Club\"\x00\x120\n" +
	"\x04list\x12\x16.google.protobuf.Empty\x1a\f.grpc.Person\"\x000\x01\x12$\n" +
	"\x04post\x12\f.grpc.Person\x1a\n" +
	".grpc.Club\"\x00(\x01\x12&\n" +
	"\x04flow\x12\f.grpc.Person\x1a\n" +
	".grpc.Club\"\x00(\x010\x01BF\n" +
	"\x17com.icodesoftware.protoB\x12ClubServiceFactoryZ\x17gameclustering.com/grpcb\x06proto3"

var file_club_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*Person)(nil),        // 1: grpc.Person
	(*Club)(nil),          // 2: grpc.Club
}
var file_club_service_proto_depIdxs = []int32{
	0, // 0: grpc.ClubService.club:input_type -> google.protobuf.Empty
	1, // 1: grpc.ClubService.register:input_type -> grpc.Person
	1, // 2: grpc.ClubService.unregister:input_type -> grpc.Person
	0, // 3: grpc.ClubService.list:input_type -> google.protobuf.Empty
	1, // 4: grpc.ClubService.post:input_type -> grpc.Person
	1, // 5: grpc.ClubService.flow:input_type -> grpc.Person
	2, // 6: grpc.ClubService.club:output_type -> grpc.Club
	2, // 7: grpc.ClubService.register:output_type -> grpc.Club
	2, // 8: grpc.ClubService.unregister:output_type -> grpc.Club
	1, // 9: grpc.ClubService.list:output_type -> grpc.Person
	2, // 10: grpc.ClubService.post:output_type -> grpc.Club
	2, // 11: grpc.ClubService.flow:output_type -> grpc.Club
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_club_service_proto_init() }
func file_club_service_proto_init() {
	if File_club_service_proto != nil {
		return
	}
	file_person_proto_init()
	file_club_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_club_service_proto_rawDesc), len(file_club_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_club_service_proto_goTypes,
		DependencyIndexes: file_club_service_proto_depIdxs,
	}.Build()
	File_club_service_proto = out.File
	file_club_service_proto_goTypes = nil
	file_club_service_proto_depIdxs = nil
}
