// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: member_type.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberType int32

const (
	MemberType_Iron    MemberType = 0
	MemberType_Silver  MemberType = 1
	MemberType_Gold    MemberType = 2
	MemberType_Diamond MemberType = 3
)

// Enum value maps for MemberType.
var (
	MemberType_name = map[int32]string{
		0: "Iron",
		1: "Silver",
		2: "Gold",
		3: "Diamond",
	}
	MemberType_value = map[string]int32{
		"Iron":    0,
		"Silver":  1,
		"Gold":    2,
		"Diamond": 3,
	}
)

func (x MemberType) Enum() *MemberType {
	p := new(MemberType)
	*p = x
	return p
}

func (x MemberType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberType) Descriptor() protoreflect.EnumDescriptor {
	return file_member_type_proto_enumTypes[0].Descriptor()
}

func (MemberType) Type() protoreflect.EnumType {
	return &file_member_type_proto_enumTypes[0]
}

func (x MemberType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberType.Descriptor instead.
func (MemberType) EnumDescriptor() ([]byte, []int) {
	return file_member_type_proto_rawDescGZIP(), []int{0}
}

var File_member_type_proto protoreflect.FileDescriptor

const file_member_type_proto_rawDesc = "" +
	"\n" +
	"\x11member_type.proto\x12\x04grpc*9\n" +
	"\n" +
	"MemberType\x12\b\n" +
	"\x04Iron\x10\x00\x12\n" +
	"\n" +
	"\x06Silver\x10\x01\x12\b\n" +
	"\x04Gold\x10\x02\x12\v\n" +
	"\aDiamond\x10\x03BE\n" +
	"\x17com.icodesoftware.protoB\x11MemberTypeFactoryZ\x17gameclustering.com/grpcb\x06proto3"

var (
	file_member_type_proto_rawDescOnce sync.Once
	file_member_type_proto_rawDescData []byte
)

func file_member_type_proto_rawDescGZIP() []byte {
	file_member_type_proto_rawDescOnce.Do(func() {
		file_member_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_member_type_proto_rawDesc), len(file_member_type_proto_rawDesc)))
	})
	return file_member_type_proto_rawDescData
}

var file_member_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_member_type_proto_goTypes = []any{
	(MemberType)(0), // 0: grpc.MemberType
}
var file_member_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_member_type_proto_init() }
func file_member_type_proto_init() {
	if File_member_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_member_type_proto_rawDesc), len(file_member_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_member_type_proto_goTypes,
		DependencyIndexes: file_member_type_proto_depIdxs,
		EnumInfos:         file_member_type_proto_enumTypes,
	}.Build()
	File_member_type_proto = out.File
	file_member_type_proto_goTypes = nil
	file_member_type_proto_depIdxs = nil
}
