// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: auth_key.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Jwt           string                 `protobuf:"bytes,3,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Cipher        string                 `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Gcp           *GcpAccess             `protobuf:"bytes,5,opt,name=gcp,proto3" json:"gcp,omitempty"`
	Git           *GitAccess             `protobuf:"bytes,6,opt,name=git,proto3" json:"git,omitempty"`
	Sql           *SqlAccess             `protobuf:"bytes,7,opt,name=sql,proto3" json:"sql,omitempty"`
	Key           string                 `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	Cert          string                 `protobuf:"bytes,9,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthKey) Reset() {
	*x = AuthKey{}
	mi := &file_auth_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthKey) ProtoMessage() {}

func (x *AuthKey) ProtoReflect() protoreflect.Message {
	mi := &file_auth_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthKey.ProtoReflect.Descriptor instead.
func (*AuthKey) Descriptor() ([]byte, []int) {
	return file_auth_key_proto_rawDescGZIP(), []int{0}
}

func (x *AuthKey) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *AuthKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthKey) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *AuthKey) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *AuthKey) GetGcp() *GcpAccess {
	if x != nil {
		return x.Gcp
	}
	return nil
}

func (x *AuthKey) GetGit() *GitAccess {
	if x != nil {
		return x.Git
	}
	return nil
}

func (x *AuthKey) GetSql() *SqlAccess {
	if x != nil {
		return x.Sql
	}
	return nil
}

func (x *AuthKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuthKey) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

var File_auth_key_proto protoreflect.FileDescriptor

const file_auth_key_proto_rawDesc = "" +
	"\n" +
	"\x0eauth_key.proto\x12\bprotocol\x1a\x10gcp_access.proto\x1a\x10git_access.proto\x1a\x10sql_access.proto\"\xfc\x01\n" +
	"\aAuthKey\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03jwt\x18\x03 \x01(\tR\x03jwt\x12\x16\n" +
	"\x06cipher\x18\x04 \x01(\tR\x06cipher\x12%\n" +
	"\x03gcp\x18\x05 \x01(\v2\x13.protocol.GcpAccessR\x03gcp\x12%\n" +
	"\x03git\x18\x06 \x01(\v2\x13.protocol.GitAccessR\x03git\x12%\n" +
	"\x03sql\x18\a \x01(\v2\x13.protocol.SqlAccessR\x03sql\x12\x10\n" +
	"\x03key\x18\b \x01(\tR\x03key\x12\x12\n" +
	"\x04cert\x18\t \x01(\tR\x04certBO\n" +
	"\x17com.icodesoftware.protoB\x0eAuthKeyFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_auth_key_proto_rawDescOnce sync.Once
	file_auth_key_proto_rawDescData []byte
)

func file_auth_key_proto_rawDescGZIP() []byte {
	file_auth_key_proto_rawDescOnce.Do(func() {
		file_auth_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_key_proto_rawDesc), len(file_auth_key_proto_rawDesc)))
	})
	return file_auth_key_proto_rawDescData
}

var file_auth_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_key_proto_goTypes = []any{
	(*AuthKey)(nil),   // 0: protocol.AuthKey
	(*GcpAccess)(nil), // 1: protocol.GcpAccess
	(*GitAccess)(nil), // 2: protocol.GitAccess
	(*SqlAccess)(nil), // 3: protocol.SqlAccess
}
var file_auth_key_proto_depIdxs = []int32{
	1, // 0: protocol.AuthKey.gcp:type_name -> protocol.GcpAccess
	2, // 1: protocol.AuthKey.git:type_name -> protocol.GitAccess
	3, // 2: protocol.AuthKey.sql:type_name -> protocol.SqlAccess
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_key_proto_init() }
func file_auth_key_proto_init() {
	if File_auth_key_proto != nil {
		return
	}
	file_gcp_access_proto_init()
	file_git_access_proto_init()
	file_sql_access_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_key_proto_rawDesc), len(file_auth_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_key_proto_goTypes,
		DependencyIndexes: file_auth_key_proto_depIdxs,
		MessageInfos:      file_auth_key_proto_msgTypes,
	}.Build()
	File_auth_key_proto = out.File
	file_auth_key_proto_goTypes = nil
	file_auth_key_proto_depIdxs = nil
}
