// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: auth_key.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Size          uint32                 `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
	Jwt           []byte                 `protobuf:"bytes,3,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Cipher        []byte                 `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Key           []byte                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthKey) Reset() {
	*x = AuthKey{}
	mi := &file_auth_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthKey) ProtoMessage() {}

func (x *AuthKey) ProtoReflect() protoreflect.Message {
	mi := &file_auth_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthKey.ProtoReflect.Descriptor instead.
func (*AuthKey) Descriptor() ([]byte, []int) {
	return file_auth_key_proto_rawDescGZIP(), []int{0}
}

func (x *AuthKey) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *AuthKey) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AuthKey) GetJwt() []byte {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *AuthKey) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

func (x *AuthKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_auth_key_proto protoreflect.FileDescriptor

const file_auth_key_proto_rawDesc = "" +
	"\n" +
	"\x0eauth_key.proto\x12\bprotocol\"s\n" +
	"\aAuthKey\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x12\n" +
	"\x04size\x18\x02 \x01(\aR\x04size\x12\x10\n" +
	"\x03jwt\x18\x03 \x01(\fR\x03jwt\x12\x16\n" +
	"\x06cipher\x18\x04 \x01(\fR\x06cipher\x12\x10\n" +
	"\x03key\x18\x05 \x01(\fR\x03keyBO\n" +
	"\x17com.icodesoftware.protoB\x0eAuthKeyFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_auth_key_proto_rawDescOnce sync.Once
	file_auth_key_proto_rawDescData []byte
)

func file_auth_key_proto_rawDescGZIP() []byte {
	file_auth_key_proto_rawDescOnce.Do(func() {
		file_auth_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_key_proto_rawDesc), len(file_auth_key_proto_rawDesc)))
	})
	return file_auth_key_proto_rawDescData
}

var file_auth_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_key_proto_goTypes = []any{
	(*AuthKey)(nil), // 0: protocol.AuthKey
}
var file_auth_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_key_proto_init() }
func file_auth_key_proto_init() {
	if File_auth_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_key_proto_rawDesc), len(file_auth_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_key_proto_goTypes,
		DependencyIndexes: file_auth_key_proto_depIdxs,
		MessageInfos:      file_auth_key_proto_msgTypes,
	}.Build()
	File_auth_key_proto = out.File
	file_auth_key_proto_goTypes = nil
	file_auth_key_proto_depIdxs = nil
}
