// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: commodity.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commodity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TypeId        string                 `protobuf:"bytes,3,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Rechargeable  bool                   `protobuf:"varint,4,opt,name=rechargeable,proto3" json:"rechargeable,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commodity) Reset() {
	*x = Commodity{}
	mi := &file_commodity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commodity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commodity) ProtoMessage() {}

func (x *Commodity) ProtoReflect() protoreflect.Message {
	mi := &file_commodity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commodity.ProtoReflect.Descriptor instead.
func (*Commodity) Descriptor() ([]byte, []int) {
	return file_commodity_proto_rawDescGZIP(), []int{0}
}

func (x *Commodity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Commodity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Commodity) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Commodity) GetRechargeable() bool {
	if x != nil {
		return x.Rechargeable
	}
	return false
}

func (x *Commodity) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_commodity_proto protoreflect.FileDescriptor

const file_commodity_proto_rawDesc = "" +
	"\n" +
	"\x0fcommodity.proto\x12\bprotocol\"\x87\x01\n" +
	"\tCommodity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06typeId\x18\x03 \x01(\tR\x06typeId\x12\"\n" +
	"\frechargeable\x18\x04 \x01(\bR\frechargeable\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amountBQ\n" +
	"\x17com.icodesoftware.protoB\x10CommodityFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_commodity_proto_rawDescOnce sync.Once
	file_commodity_proto_rawDescData []byte
)

func file_commodity_proto_rawDescGZIP() []byte {
	file_commodity_proto_rawDescOnce.Do(func() {
		file_commodity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commodity_proto_rawDesc), len(file_commodity_proto_rawDesc)))
	})
	return file_commodity_proto_rawDescData
}

var file_commodity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commodity_proto_goTypes = []any{
	(*Commodity)(nil), // 0: protocol.Commodity
}
var file_commodity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commodity_proto_init() }
func file_commodity_proto_init() {
	if File_commodity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commodity_proto_rawDesc), len(file_commodity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commodity_proto_goTypes,
		DependencyIndexes: file_commodity_proto_depIdxs,
		MessageInfos:      file_commodity_proto_msgTypes,
	}.Build()
	File_commodity_proto = out.File
	file_commodity_proto_goTypes = nil
	file_commodity_proto_depIdxs = nil
}
