// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: data_service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_data_service_proto protoreflect.FileDescriptor

const file_data_service_proto_rawDesc = "" +
	"\n" +
	"\x12data_service.proto\x12\bprotocol\x1a\n" +
	"data.proto\x1a\rrequest.proto\x1a\x0eresponse.proto\x1a\x10data_batch.proto\x1a\x0fhash_node.proto2\xe1\x02\n" +
	"\vDataService\x12*\n" +
	"\x03get\x12\x11.protocol.Request\x1a\x0e.protocol.Data\"\x00\x12+\n" +
	"\x03set\x12\x0e.protocol.Data\x1a\x12.protocol.Response\"\x00\x122\n" +
	"\x04pull\x12\x11.protocol.Request\x1a\x13.protocol.DataBatch\"\x000\x01\x12.\n" +
	"\x06create\x12\x0e.protocol.Data\x1a\x12.protocol.Response\"\x00\x12.\n" +
	"\x06update\x12\x0e.protocol.Data\x1a\x12.protocol.Response\"\x00\x12.\n" +
	"\x06delete\x12\x0e.protocol.Data\x1a\x12.protocol.Response\"\x00\x125\n" +
	"\bhashRing\x12\x11.protocol.Request\x1a\x12.protocol.HashNode\"\x000\x01BS\n" +
	"\x17com.icodesoftware.protoB\x12DataServiceFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var file_data_service_proto_goTypes = []any{
	(*Request)(nil),   // 0: protocol.Request
	(*Data)(nil),      // 1: protocol.Data
	(*Response)(nil),  // 2: protocol.Response
	(*DataBatch)(nil), // 3: protocol.DataBatch
	(*HashNode)(nil),  // 4: protocol.HashNode
}
var file_data_service_proto_depIdxs = []int32{
	0, // 0: protocol.DataService.get:input_type -> protocol.Request
	1, // 1: protocol.DataService.set:input_type -> protocol.Data
	0, // 2: protocol.DataService.pull:input_type -> protocol.Request
	1, // 3: protocol.DataService.create:input_type -> protocol.Data
	1, // 4: protocol.DataService.update:input_type -> protocol.Data
	1, // 5: protocol.DataService.delete:input_type -> protocol.Data
	0, // 6: protocol.DataService.hashRing:input_type -> protocol.Request
	1, // 7: protocol.DataService.get:output_type -> protocol.Data
	2, // 8: protocol.DataService.set:output_type -> protocol.Response
	3, // 9: protocol.DataService.pull:output_type -> protocol.DataBatch
	2, // 10: protocol.DataService.create:output_type -> protocol.Response
	2, // 11: protocol.DataService.update:output_type -> protocol.Response
	2, // 12: protocol.DataService.delete:output_type -> protocol.Response
	4, // 13: protocol.DataService.hashRing:output_type -> protocol.HashNode
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_service_proto_init() }
func file_data_service_proto_init() {
	if File_data_service_proto != nil {
		return
	}
	file_data_proto_init()
	file_request_proto_init()
	file_response_proto_init()
	file_data_batch_proto_init()
	file_hash_node_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_service_proto_rawDesc), len(file_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_service_proto_goTypes,
		DependencyIndexes: file_data_service_proto_depIdxs,
	}.Build()
	File_data_service_proto = out.File
	file_data_service_proto_goTypes = nil
	file_data_service_proto_depIdxs = nil
}
