// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: data_set.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"fixed32,1,opt,name=size,proto3" json:"size,omitempty"`
	List          []*Data                `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSet) Reset() {
	*x = DataSet{}
	mi := &file_data_set_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSet) ProtoMessage() {}

func (x *DataSet) ProtoReflect() protoreflect.Message {
	mi := &file_data_set_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSet.ProtoReflect.Descriptor instead.
func (*DataSet) Descriptor() ([]byte, []int) {
	return file_data_set_proto_rawDescGZIP(), []int{0}
}

func (x *DataSet) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DataSet) GetList() []*Data {
	if x != nil {
		return x.List
	}
	return nil
}

var File_data_set_proto protoreflect.FileDescriptor

const file_data_set_proto_rawDesc = "" +
	"\n" +
	"\x0edata_set.proto\x12\bprotocol\x1a\n" +
	"data.proto\"A\n" +
	"\aDataSet\x12\x12\n" +
	"\x04size\x18\x01 \x01(\aR\x04size\x12\"\n" +
	"\x04list\x18\x02 \x03(\v2\x0e.protocol.DataR\x04listBO\n" +
	"\x17com.icodesoftware.protoB\x0eDataSetFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_data_set_proto_rawDescOnce sync.Once
	file_data_set_proto_rawDescData []byte
)

func file_data_set_proto_rawDescGZIP() []byte {
	file_data_set_proto_rawDescOnce.Do(func() {
		file_data_set_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_set_proto_rawDesc), len(file_data_set_proto_rawDesc)))
	})
	return file_data_set_proto_rawDescData
}

var file_data_set_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_data_set_proto_goTypes = []any{
	(*DataSet)(nil), // 0: protocol.DataSet
	(*Data)(nil),    // 1: protocol.Data
}
var file_data_set_proto_depIdxs = []int32{
	1, // 0: protocol.DataSet.list:type_name -> protocol.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_set_proto_init() }
func file_data_set_proto_init() {
	if File_data_set_proto != nil {
		return
	}
	file_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_set_proto_rawDesc), len(file_data_set_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_set_proto_goTypes,
		DependencyIndexes: file_data_set_proto_depIdxs,
		MessageInfos:      file_data_set_proto_msgTypes,
	}.Build()
	File_data_set_proto = out.File
	file_data_set_proto_goTypes = nil
	file_data_set_proto_depIdxs = nil
}
