// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: gcp_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GcpAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iam           string                 `protobuf:"bytes,1,opt,name=iam,proto3" json:"iam,omitempty"`
	Ssh           string                 `protobuf:"bytes,2,opt,name=ssh,proto3" json:"ssh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpAccess) Reset() {
	*x = GcpAccess{}
	mi := &file_gcp_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpAccess) ProtoMessage() {}

func (x *GcpAccess) ProtoReflect() protoreflect.Message {
	mi := &file_gcp_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpAccess.ProtoReflect.Descriptor instead.
func (*GcpAccess) Descriptor() ([]byte, []int) {
	return file_gcp_access_proto_rawDescGZIP(), []int{0}
}

func (x *GcpAccess) GetIam() string {
	if x != nil {
		return x.Iam
	}
	return ""
}

func (x *GcpAccess) GetSsh() string {
	if x != nil {
		return x.Ssh
	}
	return ""
}

var File_gcp_access_proto protoreflect.FileDescriptor

const file_gcp_access_proto_rawDesc = "" +
	"\n" +
	"\x10gcp_access.proto\x12\bprotocol\"/\n" +
	"\tGcpAccess\x12\x10\n" +
	"\x03iam\x18\x01 \x01(\tR\x03iam\x12\x10\n" +
	"\x03ssh\x18\x02 \x01(\tR\x03sshBQ\n" +
	"\x17com.icodesoftware.protoB\x10GcpAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_gcp_access_proto_rawDescOnce sync.Once
	file_gcp_access_proto_rawDescData []byte
)

func file_gcp_access_proto_rawDescGZIP() []byte {
	file_gcp_access_proto_rawDescOnce.Do(func() {
		file_gcp_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gcp_access_proto_rawDesc), len(file_gcp_access_proto_rawDesc)))
	})
	return file_gcp_access_proto_rawDescData
}

var file_gcp_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gcp_access_proto_goTypes = []any{
	(*GcpAccess)(nil), // 0: protocol.GcpAccess
}
var file_gcp_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcp_access_proto_init() }
func file_gcp_access_proto_init() {
	if File_gcp_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcp_access_proto_rawDesc), len(file_gcp_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcp_access_proto_goTypes,
		DependencyIndexes: file_gcp_access_proto_depIdxs,
		MessageInfos:      file_gcp_access_proto_msgTypes,
	}.Build()
	File_gcp_access_proto = out.File
	file_gcp_access_proto_goTypes = nil
	file_gcp_access_proto_depIdxs = nil
}
