// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: git_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Org           string                 `protobuf:"bytes,5,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitAccess) Reset() {
	*x = GitAccess{}
	mi := &file_git_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitAccess) ProtoMessage() {}

func (x *GitAccess) ProtoReflect() protoreflect.Message {
	mi := &file_git_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitAccess.ProtoReflect.Descriptor instead.
func (*GitAccess) Descriptor() ([]byte, []int) {
	return file_git_access_proto_rawDescGZIP(), []int{0}
}

func (x *GitAccess) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GitAccess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GitAccess) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GitAccess) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GitAccess) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

var File_git_access_proto protoreflect.FileDescriptor

const file_git_access_proto_rawDesc = "" +
	"\n" +
	"\x10git_access.proto\x12\bprotocol\"o\n" +
	"\tGitAccess\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x10\n" +
	"\x03org\x18\x05 \x01(\tR\x03orgBQ\n" +
	"\x17com.icodesoftware.protoB\x10GitAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_git_access_proto_rawDescOnce sync.Once
	file_git_access_proto_rawDescData []byte
)

func file_git_access_proto_rawDescGZIP() []byte {
	file_git_access_proto_rawDescOnce.Do(func() {
		file_git_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_git_access_proto_rawDesc), len(file_git_access_proto_rawDesc)))
	})
	return file_git_access_proto_rawDescData
}

var file_git_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_git_access_proto_goTypes = []any{
	(*GitAccess)(nil), // 0: protocol.GitAccess
}
var file_git_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_git_access_proto_init() }
func file_git_access_proto_init() {
	if File_git_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_git_access_proto_rawDesc), len(file_git_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_git_access_proto_goTypes,
		DependencyIndexes: file_git_access_proto_depIdxs,
		MessageInfos:      file_git_access_proto_msgTypes,
	}.Build()
	File_git_access_proto = out.File
	file_git_access_proto_goTypes = nil
	file_git_access_proto_depIdxs = nil
}
