// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: hash_node.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          uint32                 `protobuf:"fixed32,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Meta          string                 `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashNode) Reset() {
	*x = HashNode{}
	mi := &file_hash_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashNode) ProtoMessage() {}

func (x *HashNode) ProtoReflect() protoreflect.Message {
	mi := &file_hash_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashNode.ProtoReflect.Descriptor instead.
func (*HashNode) Descriptor() ([]byte, []int) {
	return file_hash_node_proto_rawDescGZIP(), []int{0}
}

func (x *HashNode) GetHash() uint32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *HashNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HashNode) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HashNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HashNode) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

var File_hash_node_proto protoreflect.FileDescriptor

const file_hash_node_proto_rawDesc = "" +
	"\n" +
	"\x0fhash_node.proto\x12\bprotocol\"|\n" +
	"\bHashNode\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\aR\x04hash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04meta\x18\x05 \x01(\tR\x04metaBP\n" +
	"\x17com.icodesoftware.protoB\x0fHashNodeFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_hash_node_proto_rawDescOnce sync.Once
	file_hash_node_proto_rawDescData []byte
)

func file_hash_node_proto_rawDescGZIP() []byte {
	file_hash_node_proto_rawDescOnce.Do(func() {
		file_hash_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hash_node_proto_rawDesc), len(file_hash_node_proto_rawDesc)))
	})
	return file_hash_node_proto_rawDescData
}

var file_hash_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hash_node_proto_goTypes = []any{
	(*HashNode)(nil), // 0: protocol.HashNode
}
var file_hash_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hash_node_proto_init() }
func file_hash_node_proto_init() {
	if File_hash_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hash_node_proto_rawDesc), len(file_hash_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hash_node_proto_goTypes,
		DependencyIndexes: file_hash_node_proto_depIdxs,
		MessageInfos:      file_hash_node_proto_msgTypes,
	}.Build()
	File_hash_node_proto = out.File
	file_hash_node_proto_goTypes = nil
	file_hash_node_proto_depIdxs = nil
}
