// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: header.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"fixed64,1,opt,name=revision,proto3" json:"revision,omitempty"`
	FactoryId     uint32                 `protobuf:"fixed32,2,opt,name=factoryId,proto3" json:"factoryId,omitempty"`
	ClassId       uint32                 `protobuf:"fixed32,3,opt,name=classId,proto3" json:"classId,omitempty"`
	Timestamp     uint64                 `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          uint32                 `protobuf:"fixed32,5,opt,name=size,proto3" json:"size,omitempty"`
	Updatable     bool                   `protobuf:"varint,6,opt,name=updatable,proto3" json:"updatable,omitempty"`
	State         uint32                 `protobuf:"fixed32,7,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Header) GetFactoryId() uint32 {
	if x != nil {
		return x.FactoryId
	}
	return 0
}

func (x *Header) GetClassId() uint32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Header) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Header) GetUpdatable() bool {
	if x != nil {
		return x.Updatable
	}
	return false
}

func (x *Header) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_header_proto protoreflect.FileDescriptor

const file_header_proto_rawDesc = "" +
	"\n" +
	"\fheader.proto\x12\bprotocol\"\xc2\x01\n" +
	"\x06Header\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x06R\brevision\x12\x1c\n" +
	"\tfactoryId\x18\x02 \x01(\aR\tfactoryId\x12\x18\n" +
	"\aclassId\x18\x03 \x01(\aR\aclassId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x06R\ttimestamp\x12\x12\n" +
	"\x04size\x18\x05 \x01(\aR\x04size\x12\x1c\n" +
	"\tupdatable\x18\x06 \x01(\bR\tupdatable\x12\x14\n" +
	"\x05state\x18\a \x01(\aR\x05stateBN\n" +
	"\x17com.icodesoftware.protoB\rHeaderFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_header_proto_rawDescOnce sync.Once
	file_header_proto_rawDescData []byte
)

func file_header_proto_rawDescGZIP() []byte {
	file_header_proto_rawDescOnce.Do(func() {
		file_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_header_proto_rawDesc), len(file_header_proto_rawDesc)))
	})
	return file_header_proto_rawDescData
}

var file_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_header_proto_goTypes = []any{
	(*Header)(nil), // 0: protocol.Header
}
var file_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_header_proto_init() }
func file_header_proto_init() {
	if File_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_header_proto_rawDesc), len(file_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_header_proto_goTypes,
		DependencyIndexes: file_header_proto_depIdxs,
		MessageInfos:      file_header_proto_msgTypes,
	}.Build()
	File_header_proto = out.File
	file_header_proto_goTypes = nil
	file_header_proto_depIdxs = nil
}
