// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: login_event.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SystemId      uint64                 `protobuf:"fixed64,2,opt,name=systemId,proto3" json:"systemId,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginEvent) Reset() {
	*x = LoginEvent{}
	mi := &file_login_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEvent) ProtoMessage() {}

func (x *LoginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_login_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEvent.ProtoReflect.Descriptor instead.
func (*LoginEvent) Descriptor() ([]byte, []int) {
	return file_login_event_proto_rawDescGZIP(), []int{0}
}

func (x *LoginEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginEvent) GetSystemId() uint64 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *LoginEvent) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *LoginEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_login_event_proto protoreflect.FileDescriptor

const file_login_event_proto_rawDesc = "" +
	"\n" +
	"\x11login_event.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n" +
	"\n" +
	"LoginEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bsystemId\x18\x02 \x01(\x06R\bsystemId\x126\n" +
	"\bdateTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06sourceBR\n" +
	"\x17com.icodesoftware.protoB\x11LoginEventFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_login_event_proto_rawDescOnce sync.Once
	file_login_event_proto_rawDescData []byte
)

func file_login_event_proto_rawDescGZIP() []byte {
	file_login_event_proto_rawDescOnce.Do(func() {
		file_login_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_event_proto_rawDesc), len(file_login_event_proto_rawDesc)))
	})
	return file_login_event_proto_rawDescData
}

var file_login_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_login_event_proto_goTypes = []any{
	(*LoginEvent)(nil),            // 0: protocol.LoginEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_login_event_proto_depIdxs = []int32{
	1, // 0: protocol.LoginEvent.dateTime:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_login_event_proto_init() }
func file_login_event_proto_init() {
	if File_login_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_event_proto_rawDesc), len(file_login_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_event_proto_goTypes,
		DependencyIndexes: file_login_event_proto_depIdxs,
		MessageInfos:      file_login_event_proto_msgTypes,
	}.Build()
	File_login_event_proto = out.File
	file_login_event_proto_goTypes = nil
	file_login_event_proto_depIdxs = nil
}
