// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: login_object.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Id            uint32                 `protobuf:"fixed32,3,opt,name=id,proto3" json:"id,omitempty"`
	SystemId      uint64                 `protobuf:"fixed64,4,opt,name=systemId,proto3" json:"systemId,omitempty"`
	ReferenceId   uint32                 `protobuf:"fixed32,5,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	AccessControl uint32                 `protobuf:"fixed32,6,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginObject) Reset() {
	*x = LoginObject{}
	mi := &file_login_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginObject) ProtoMessage() {}

func (x *LoginObject) ProtoReflect() protoreflect.Message {
	mi := &file_login_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginObject.ProtoReflect.Descriptor instead.
func (*LoginObject) Descriptor() ([]byte, []int) {
	return file_login_object_proto_rawDescGZIP(), []int{0}
}

func (x *LoginObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginObject) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginObject) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginObject) GetSystemId() uint64 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *LoginObject) GetReferenceId() uint32 {
	if x != nil {
		return x.ReferenceId
	}
	return 0
}

func (x *LoginObject) GetAccessControl() uint32 {
	if x != nil {
		return x.AccessControl
	}
	return 0
}

var File_login_object_proto protoreflect.FileDescriptor

const file_login_object_proto_rawDesc = "" +
	"\n" +
	"\x12login_object.proto\x12\bprotocol\"\xb1\x01\n" +
	"\vLoginObject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\aR\x02id\x12\x1a\n" +
	"\bsystemId\x18\x04 \x01(\x06R\bsystemId\x12 \n" +
	"\vreferenceId\x18\x05 \x01(\aR\vreferenceId\x12$\n" +
	"\raccessControl\x18\x06 \x01(\aR\raccessControlBS\n" +
	"\x17com.icodesoftware.protoB\x12LoginObjectFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_login_object_proto_rawDescOnce sync.Once
	file_login_object_proto_rawDescData []byte
)

func file_login_object_proto_rawDescGZIP() []byte {
	file_login_object_proto_rawDescOnce.Do(func() {
		file_login_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_object_proto_rawDesc), len(file_login_object_proto_rawDesc)))
	})
	return file_login_object_proto_rawDescData
}

var file_login_object_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_login_object_proto_goTypes = []any{
	(*LoginObject)(nil), // 0: protocol.LoginObject
}
var file_login_object_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_object_proto_init() }
func file_login_object_proto_init() {
	if File_login_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_object_proto_rawDesc), len(file_login_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_object_proto_goTypes,
		DependencyIndexes: file_login_object_proto_depIdxs,
		MessageInfos:      file_login_object_proto_msgTypes,
	}.Build()
	File_login_object_proto = out.File
	file_login_object_proto_goTypes = nil
	file_login_object_proto_depIdxs = nil
}
