// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: mail.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opt           uint32                 `protobuf:"fixed32,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Topic         *Topic                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mail) Reset() {
	*x = Mail{}
	mi := &file_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

func (x *Mail) GetOpt() uint32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *Mail) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Mail) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_mail_proto protoreflect.FileDescriptor

const file_mail_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mail.proto\x12\bprotocol\x1a\vtopic.proto\x1a\x11transaction.proto\"x\n" +
	"\x04Mail\x12\x10\n" +
	"\x03opt\x18\x01 \x01(\aR\x03opt\x12%\n" +
	"\x05topic\x18\x02 \x01(\v2\x0f.protocol.TopicR\x05topic\x127\n" +
	"\vtransaction\x18\x03 \x01(\v2\x15.protocol.TransactionR\vtransactionBL\n" +
	"\x17com.icodesoftware.protoB\vMailFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData []byte
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)))
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mail_proto_goTypes = []any{
	(*Mail)(nil),        // 0: protocol.Mail
	(*Topic)(nil),       // 1: protocol.Topic
	(*Transaction)(nil), // 2: protocol.Transaction
}
var file_mail_proto_depIdxs = []int32{
	1, // 0: protocol.Mail.topic:type_name -> protocol.Topic
	2, // 1: protocol.Mail.transaction:type_name -> protocol.Transaction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	file_topic_proto_init()
	file_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
