// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: message_event.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_message_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_message_event_proto_rawDescGZIP(), []int{0}
}

func (x *MessageEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageEvent) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *MessageEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_message_event_proto protoreflect.FileDescriptor

const file_message_event_proto_rawDesc = "" +
	"\n" +
	"\x13message_event.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\fMessageEvent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\bdateTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06sourceBT\n" +
	"\x17com.icodesoftware.protoB\x13MessageEventFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_message_event_proto_rawDescOnce sync.Once
	file_message_event_proto_rawDescData []byte
)

func file_message_event_proto_rawDescGZIP() []byte {
	file_message_event_proto_rawDescOnce.Do(func() {
		file_message_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_event_proto_rawDesc), len(file_message_event_proto_rawDesc)))
	})
	return file_message_event_proto_rawDescData
}

var file_message_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_event_proto_goTypes = []any{
	(*MessageEvent)(nil),          // 0: protocol.MessageEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_message_event_proto_depIdxs = []int32{
	1, // 0: protocol.MessageEvent.dateTime:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_event_proto_init() }
func file_message_event_proto_init() {
	if File_message_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_event_proto_rawDesc), len(file_message_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_event_proto_goTypes,
		DependencyIndexes: file_message_event_proto_depIdxs,
		MessageInfos:      file_message_event_proto_msgTypes,
	}.Build()
	File_message_event_proto = out.File
	file_message_event_proto_goTypes = nil
	file_message_event_proto_depIdxs = nil
}
