// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: meta.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        uint32                 `protobuf:"fixed32,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TaskId        uint64                 `protobuf:"fixed64,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	JobId         uint64                 `protobuf:"fixed64,3,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Id            uint64                 `protobuf:"fixed64,4,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Tag           string                 `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Timeout       uint32                 `protobuf:"fixed32,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retries       uint32                 `protobuf:"fixed32,9,opt,name=retries,proto3" json:"retries,omitempty"`
	State         uint32                 `protobuf:"fixed32,10,opt,name=state,proto3" json:"state,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=time,proto3" json:"time,omitempty"`
	Persistent    bool                   `protobuf:"varint,12,opt,name=persistent,proto3" json:"persistent,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetPrefix() uint32 {
	if x != nil {
		return x.Prefix
	}
	return 0
}

func (x *Meta) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Meta) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *Meta) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Meta) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Meta) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Meta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Meta) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Meta) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Meta) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Meta) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Meta) GetPersistent() bool {
	if x != nil {
		return x.Persistent
	}
	return false
}

func (x *Meta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_meta_proto protoreflect.FileDescriptor

const file_meta_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"meta.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x02\n" +
	"\x04Meta\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\aR\x06prefix\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\x06R\x06taskId\x12\x14\n" +
	"\x05jobId\x18\x03 \x01(\x06R\x05jobId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x06R\x02id\x12\x16\n" +
	"\x06nodeId\x18\x05 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x18\n" +
	"\atimeout\x18\b \x01(\aR\atimeout\x12\x18\n" +
	"\aretries\x18\t \x01(\aR\aretries\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\aR\x05state\x12.\n" +
	"\x04time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1e\n" +
	"\n" +
	"persistent\x18\f \x01(\bR\n" +
	"persistent\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescriptionBL\n" +
	"\x17com.icodesoftware.protoB\vMetaFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData []byte
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)))
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_proto_goTypes = []any{
	(*Meta)(nil),                  // 0: protocol.Meta
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_meta_proto_depIdxs = []int32{
	1, // 0: protocol.Meta.time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
