// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: postoffice_service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_postoffice_service_proto protoreflect.FileDescriptor

const file_postoffice_service_proto_rawDesc = "" +
	"\n" +
	"\x18postoffice_service.proto\x12\bprotocol\x1a\rrequest.proto\x1a\x0eresponse.proto\x1a\x0fhash_node.proto\x1a\vtopic.proto\x1a\n" +
	"task.proto\x1a\n" +
	"mail.proto2\xc5\x04\n" +
	"\x11PostofficeService\x125\n" +
	"\bhashRing\x12\x11.protocol.Request\x1a\x12.protocol.HashNode\"\x000\x01\x124\n" +
	"\akeyRing\x12\x11.protocol.Request\x1a\x12.protocol.HashNode\"\x000\x01\x122\n" +
	"\arequest\x12\x11.protocol.Request\x1a\x12.protocol.Response\"\x00\x121\n" +
	"\x04list\x12\x11.protocol.Request\x1a\x12.protocol.Response\"\x000\x01\x122\n" +
	"\tsubscribe\x12\x0f.protocol.Topic\x1a\x12.protocol.Response\"\x00\x124\n" +
	"\vunsubscribe\x12\x0f.protocol.Topic\x1a\x12.protocol.Response\"\x00\x120\n" +
	"\apublish\x12\x0f.protocol.Topic\x1a\x12.protocol.Response\"\x00\x123\n" +
	"\n" +
	"disconnect\x12\x0f.protocol.Topic\x1a\x12.protocol.Response\"\x00\x12.\n" +
	"\areceive\x12\x0f.protocol.Topic\x1a\x0e.protocol.Mail\"\x000\x01\x12-\n" +
	"\x05issue\x12\x0e.protocol.Task\x1a\x12.protocol.Response\"\x00\x12,\n" +
	"\x06accept\x12\x0e.protocol.Task\x1a\x0e.protocol.Task\"\x000\x01BY\n" +
	"\x17com.icodesoftware.protoB\x18PostofficeServiceFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var file_postoffice_service_proto_goTypes = []any{
	(*Request)(nil),  // 0: protocol.Request
	(*Topic)(nil),    // 1: protocol.Topic
	(*Task)(nil),     // 2: protocol.Task
	(*HashNode)(nil), // 3: protocol.HashNode
	(*Response)(nil), // 4: protocol.Response
	(*Mail)(nil),     // 5: protocol.Mail
}
var file_postoffice_service_proto_depIdxs = []int32{
	0,  // 0: protocol.PostofficeService.hashRing:input_type -> protocol.Request
	0,  // 1: protocol.PostofficeService.keyRing:input_type -> protocol.Request
	0,  // 2: protocol.PostofficeService.request:input_type -> protocol.Request
	0,  // 3: protocol.PostofficeService.list:input_type -> protocol.Request
	1,  // 4: protocol.PostofficeService.subscribe:input_type -> protocol.Topic
	1,  // 5: protocol.PostofficeService.unsubscribe:input_type -> protocol.Topic
	1,  // 6: protocol.PostofficeService.publish:input_type -> protocol.Topic
	1,  // 7: protocol.PostofficeService.disconnect:input_type -> protocol.Topic
	1,  // 8: protocol.PostofficeService.receive:input_type -> protocol.Topic
	2,  // 9: protocol.PostofficeService.issue:input_type -> protocol.Task
	2,  // 10: protocol.PostofficeService.accept:input_type -> protocol.Task
	3,  // 11: protocol.PostofficeService.hashRing:output_type -> protocol.HashNode
	3,  // 12: protocol.PostofficeService.keyRing:output_type -> protocol.HashNode
	4,  // 13: protocol.PostofficeService.request:output_type -> protocol.Response
	4,  // 14: protocol.PostofficeService.list:output_type -> protocol.Response
	4,  // 15: protocol.PostofficeService.subscribe:output_type -> protocol.Response
	4,  // 16: protocol.PostofficeService.unsubscribe:output_type -> protocol.Response
	4,  // 17: protocol.PostofficeService.publish:output_type -> protocol.Response
	4,  // 18: protocol.PostofficeService.disconnect:output_type -> protocol.Response
	5,  // 19: protocol.PostofficeService.receive:output_type -> protocol.Mail
	4,  // 20: protocol.PostofficeService.issue:output_type -> protocol.Response
	2,  // 21: protocol.PostofficeService.accept:output_type -> protocol.Task
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_postoffice_service_proto_init() }
func file_postoffice_service_proto_init() {
	if File_postoffice_service_proto != nil {
		return
	}
	file_request_proto_init()
	file_response_proto_init()
	file_hash_node_proto_init()
	file_topic_proto_init()
	file_task_proto_init()
	file_mail_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postoffice_service_proto_rawDesc), len(file_postoffice_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_postoffice_service_proto_goTypes,
		DependencyIndexes: file_postoffice_service_proto_depIdxs,
	}.Build()
	File_postoffice_service_proto = out.File
	file_postoffice_service_proto_goTypes = nil
	file_postoffice_service_proto_depIdxs = nil
}
