// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: postoffice_service.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostofficeService_AuthKey_FullMethodName     = "/protocol.PostofficeService/authKey"
	PostofficeService_HashRing_FullMethodName    = "/protocol.PostofficeService/hashRing"
	PostofficeService_KeyRing_FullMethodName     = "/protocol.PostofficeService/keyRing"
	PostofficeService_Request_FullMethodName     = "/protocol.PostofficeService/request"
	PostofficeService_List_FullMethodName        = "/protocol.PostofficeService/list"
	PostofficeService_TopicList_FullMethodName   = "/protocol.PostofficeService/topicList"
	PostofficeService_TaskList_FullMethodName    = "/protocol.PostofficeService/taskList"
	PostofficeService_Subscribe_FullMethodName   = "/protocol.PostofficeService/subscribe"
	PostofficeService_Unsubscribe_FullMethodName = "/protocol.PostofficeService/unsubscribe"
	PostofficeService_Publish_FullMethodName     = "/protocol.PostofficeService/publish"
	PostofficeService_Disconnect_FullMethodName  = "/protocol.PostofficeService/disconnect"
	PostofficeService_Receive_FullMethodName     = "/protocol.PostofficeService/receive"
	PostofficeService_Issue_FullMethodName       = "/protocol.PostofficeService/issue"
	PostofficeService_Confirm_FullMethodName     = "/protocol.PostofficeService/confirm"
	PostofficeService_Cancel_FullMethodName      = "/protocol.PostofficeService/cancel"
	PostofficeService_Finish_FullMethodName      = "/protocol.PostofficeService/finish"
)

// PostofficeServiceClient is the client API for PostofficeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostofficeServiceClient interface {
	// auth key load
	AuthKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*AuthKey, error)
	// data delegate API
	HashRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	KeyRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Request(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	// subscription list API
	TopicList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	TaskList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// topic delegate API
	Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Response, error)
	Unsubscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Response, error)
	Publish(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error)
	Disconnect(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error)
	// mail down stream receive
	Receive(ctx context.Context, in *Topic, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Mail], error)
	// task delegate API
	Issue(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error)
	Confirm(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error)
	Cancel(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error)
	Finish(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error)
}

type postofficeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostofficeServiceClient(cc grpc.ClientConnInterface) PostofficeServiceClient {
	return &postofficeServiceClient{cc}
}

func (c *postofficeServiceClient) AuthKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*AuthKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthKey)
	err := c.cc.Invoke(ctx, PostofficeService_AuthKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) HashRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_HashRing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) KeyRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_KeyRing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Request(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) List(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PostofficeService_ServiceDesc.Streams[0], PostofficeService_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ListClient = grpc.ServerStreamingClient[Response]

func (c *postofficeServiceClient) TopicList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_TopicList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) TaskList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_TaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Unsubscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Publish(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Disconnect(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Receive(ctx context.Context, in *Topic, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Mail], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PostofficeService_ServiceDesc.Streams[1], PostofficeService_Receive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Topic, Mail]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ReceiveClient = grpc.ServerStreamingClient[Mail]

func (c *postofficeServiceClient) Issue(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Issue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Confirm(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Cancel(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Finish(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Finish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostofficeServiceServer is the server API for PostofficeService service.
// All implementations must embed UnimplementedPostofficeServiceServer
// for forward compatibility.
type PostofficeServiceServer interface {
	// auth key load
	AuthKey(context.Context, *Request) (*AuthKey, error)
	// data delegate API
	HashRing(context.Context, *Request) (*Response, error)
	KeyRing(context.Context, *Request) (*Response, error)
	Request(context.Context, *Request) (*Response, error)
	List(*Request, grpc.ServerStreamingServer[Response]) error
	// subscription list API
	TopicList(context.Context, *Request) (*Response, error)
	TaskList(context.Context, *Request) (*Response, error)
	// topic delegate API
	Subscribe(context.Context, *Subscription) (*Response, error)
	Unsubscribe(context.Context, *Subscription) (*Response, error)
	Publish(context.Context, *Topic) (*Response, error)
	Disconnect(context.Context, *Topic) (*Response, error)
	// mail down stream receive
	Receive(*Topic, grpc.ServerStreamingServer[Mail]) error
	// task delegate API
	Issue(context.Context, *Task) (*Response, error)
	Confirm(context.Context, *Meta) (*Response, error)
	Cancel(context.Context, *Meta) (*Response, error)
	Finish(context.Context, *Meta) (*Response, error)
	mustEmbedUnimplementedPostofficeServiceServer()
}

// UnimplementedPostofficeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostofficeServiceServer struct{}

func (UnimplementedPostofficeServiceServer) AuthKey(context.Context, *Request) (*AuthKey, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthKey not implemented")
}
func (UnimplementedPostofficeServiceServer) HashRing(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method HashRing not implemented")
}
func (UnimplementedPostofficeServiceServer) KeyRing(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyRing not implemented")
}
func (UnimplementedPostofficeServiceServer) Request(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedPostofficeServiceServer) List(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPostofficeServiceServer) TopicList(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TopicList not implemented")
}
func (UnimplementedPostofficeServiceServer) TaskList(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskList not implemented")
}
func (UnimplementedPostofficeServiceServer) Subscribe(context.Context, *Subscription) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPostofficeServiceServer) Unsubscribe(context.Context, *Subscription) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedPostofficeServiceServer) Publish(context.Context, *Topic) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPostofficeServiceServer) Disconnect(context.Context, *Topic) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedPostofficeServiceServer) Receive(*Topic, grpc.ServerStreamingServer[Mail]) error {
	return status.Error(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedPostofficeServiceServer) Issue(context.Context, *Task) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Issue not implemented")
}
func (UnimplementedPostofficeServiceServer) Confirm(context.Context, *Meta) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedPostofficeServiceServer) Cancel(context.Context, *Meta) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedPostofficeServiceServer) Finish(context.Context, *Meta) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Finish not implemented")
}
func (UnimplementedPostofficeServiceServer) mustEmbedUnimplementedPostofficeServiceServer() {}
func (UnimplementedPostofficeServiceServer) testEmbeddedByValue()                           {}

// UnsafePostofficeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostofficeServiceServer will
// result in compilation errors.
type UnsafePostofficeServiceServer interface {
	mustEmbedUnimplementedPostofficeServiceServer()
}

func RegisterPostofficeServiceServer(s grpc.ServiceRegistrar, srv PostofficeServiceServer) {
	// If the following call panics, it indicates UnimplementedPostofficeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostofficeService_ServiceDesc, srv)
}

func _PostofficeService_AuthKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).AuthKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_AuthKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).AuthKey(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_HashRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).HashRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_HashRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).HashRing(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_KeyRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).KeyRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_KeyRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).KeyRing(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Request(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostofficeServiceServer).List(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ListServer = grpc.ServerStreamingServer[Response]

func _PostofficeService_TopicList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).TopicList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_TopicList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).TopicList(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_TaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).TaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_TaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).TaskList(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Subscribe(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Unsubscribe(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Publish(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Disconnect(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Topic)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostofficeServiceServer).Receive(m, &grpc.GenericServerStream[Topic, Mail]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ReceiveServer = grpc.ServerStreamingServer[Mail]

func _PostofficeService_Issue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Issue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Issue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Issue(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Confirm(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Cancel(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Finish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Finish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Finish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Finish(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

// PostofficeService_ServiceDesc is the grpc.ServiceDesc for PostofficeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostofficeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.PostofficeService",
	HandlerType: (*PostofficeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "authKey",
			Handler:    _PostofficeService_AuthKey_Handler,
		},
		{
			MethodName: "hashRing",
			Handler:    _PostofficeService_HashRing_Handler,
		},
		{
			MethodName: "keyRing",
			Handler:    _PostofficeService_KeyRing_Handler,
		},
		{
			MethodName: "request",
			Handler:    _PostofficeService_Request_Handler,
		},
		{
			MethodName: "topicList",
			Handler:    _PostofficeService_TopicList_Handler,
		},
		{
			MethodName: "taskList",
			Handler:    _PostofficeService_TaskList_Handler,
		},
		{
			MethodName: "subscribe",
			Handler:    _PostofficeService_Subscribe_Handler,
		},
		{
			MethodName: "unsubscribe",
			Handler:    _PostofficeService_Unsubscribe_Handler,
		},
		{
			MethodName: "publish",
			Handler:    _PostofficeService_Publish_Handler,
		},
		{
			MethodName: "disconnect",
			Handler:    _PostofficeService_Disconnect_Handler,
		},
		{
			MethodName: "issue",
			Handler:    _PostofficeService_Issue_Handler,
		},
		{
			MethodName: "confirm",
			Handler:    _PostofficeService_Confirm_Handler,
		},
		{
			MethodName: "cancel",
			Handler:    _PostofficeService_Cancel_Handler,
		},
		{
			MethodName: "finish",
			Handler:    _PostofficeService_Finish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "list",
			Handler:       _PostofficeService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "receive",
			Handler:       _PostofficeService_Receive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "postoffice_service.proto",
}
