// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: postoffice_service.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostofficeService_HashRing_FullMethodName    = "/protocol.PostofficeService/hashRing"
	PostofficeService_KeyRing_FullMethodName     = "/protocol.PostofficeService/keyRing"
	PostofficeService_Request_FullMethodName     = "/protocol.PostofficeService/request"
	PostofficeService_List_FullMethodName        = "/protocol.PostofficeService/list"
	PostofficeService_Receive_FullMethodName     = "/protocol.PostofficeService/receive"
	PostofficeService_Subscribe_FullMethodName   = "/protocol.PostofficeService/subscribe"
	PostofficeService_Unsubscribe_FullMethodName = "/protocol.PostofficeService/unsubscribe"
	PostofficeService_Publish_FullMethodName     = "/protocol.PostofficeService/publish"
	PostofficeService_Disconnect_FullMethodName  = "/protocol.PostofficeService/disconnect"
)

// PostofficeServiceClient is the client API for PostofficeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostofficeServiceClient interface {
	// data API
	HashRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HashNode], error)
	KeyRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HashNode], error)
	Request(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	// topic API
	Receive(ctx context.Context, in *Topic, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Topic], error)
	Subscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error)
	Unsubscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error)
	Publish(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error)
	Disconnect(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error)
}

type postofficeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostofficeServiceClient(cc grpc.ClientConnInterface) PostofficeServiceClient {
	return &postofficeServiceClient{cc}
}

func (c *postofficeServiceClient) HashRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HashNode], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PostofficeService_ServiceDesc.Streams[0], PostofficeService_HashRing_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, HashNode]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_HashRingClient = grpc.ServerStreamingClient[HashNode]

func (c *postofficeServiceClient) KeyRing(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HashNode], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PostofficeService_ServiceDesc.Streams[1], PostofficeService_KeyRing_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, HashNode]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_KeyRingClient = grpc.ServerStreamingClient[HashNode]

func (c *postofficeServiceClient) Request(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) List(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PostofficeService_ServiceDesc.Streams[2], PostofficeService_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ListClient = grpc.ServerStreamingClient[Response]

func (c *postofficeServiceClient) Receive(ctx context.Context, in *Topic, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Topic], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PostofficeService_ServiceDesc.Streams[3], PostofficeService_Receive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Topic, Topic]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ReceiveClient = grpc.ServerStreamingClient[Topic]

func (c *postofficeServiceClient) Subscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Unsubscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Publish(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postofficeServiceClient) Disconnect(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PostofficeService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostofficeServiceServer is the server API for PostofficeService service.
// All implementations must embed UnimplementedPostofficeServiceServer
// for forward compatibility.
type PostofficeServiceServer interface {
	// data API
	HashRing(*Request, grpc.ServerStreamingServer[HashNode]) error
	KeyRing(*Request, grpc.ServerStreamingServer[HashNode]) error
	Request(context.Context, *Request) (*Response, error)
	List(*Request, grpc.ServerStreamingServer[Response]) error
	// topic API
	Receive(*Topic, grpc.ServerStreamingServer[Topic]) error
	Subscribe(context.Context, *Topic) (*Response, error)
	Unsubscribe(context.Context, *Topic) (*Response, error)
	Publish(context.Context, *Topic) (*Response, error)
	Disconnect(context.Context, *Topic) (*Response, error)
	mustEmbedUnimplementedPostofficeServiceServer()
}

// UnimplementedPostofficeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostofficeServiceServer struct{}

func (UnimplementedPostofficeServiceServer) HashRing(*Request, grpc.ServerStreamingServer[HashNode]) error {
	return status.Error(codes.Unimplemented, "method HashRing not implemented")
}
func (UnimplementedPostofficeServiceServer) KeyRing(*Request, grpc.ServerStreamingServer[HashNode]) error {
	return status.Error(codes.Unimplemented, "method KeyRing not implemented")
}
func (UnimplementedPostofficeServiceServer) Request(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedPostofficeServiceServer) List(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPostofficeServiceServer) Receive(*Topic, grpc.ServerStreamingServer[Topic]) error {
	return status.Error(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedPostofficeServiceServer) Subscribe(context.Context, *Topic) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPostofficeServiceServer) Unsubscribe(context.Context, *Topic) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedPostofficeServiceServer) Publish(context.Context, *Topic) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPostofficeServiceServer) Disconnect(context.Context, *Topic) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedPostofficeServiceServer) mustEmbedUnimplementedPostofficeServiceServer() {}
func (UnimplementedPostofficeServiceServer) testEmbeddedByValue()                           {}

// UnsafePostofficeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostofficeServiceServer will
// result in compilation errors.
type UnsafePostofficeServiceServer interface {
	mustEmbedUnimplementedPostofficeServiceServer()
}

func RegisterPostofficeServiceServer(s grpc.ServiceRegistrar, srv PostofficeServiceServer) {
	// If the following call panics, it indicates UnimplementedPostofficeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostofficeService_ServiceDesc, srv)
}

func _PostofficeService_HashRing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostofficeServiceServer).HashRing(m, &grpc.GenericServerStream[Request, HashNode]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_HashRingServer = grpc.ServerStreamingServer[HashNode]

func _PostofficeService_KeyRing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostofficeServiceServer).KeyRing(m, &grpc.GenericServerStream[Request, HashNode]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_KeyRingServer = grpc.ServerStreamingServer[HashNode]

func _PostofficeService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Request(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostofficeServiceServer).List(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ListServer = grpc.ServerStreamingServer[Response]

func _PostofficeService_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Topic)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostofficeServiceServer).Receive(m, &grpc.GenericServerStream[Topic, Topic]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PostofficeService_ReceiveServer = grpc.ServerStreamingServer[Topic]

func _PostofficeService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Subscribe(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Unsubscribe(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Publish(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostofficeService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostofficeServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostofficeService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostofficeServiceServer).Disconnect(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

// PostofficeService_ServiceDesc is the grpc.ServiceDesc for PostofficeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostofficeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.PostofficeService",
	HandlerType: (*PostofficeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request",
			Handler:    _PostofficeService_Request_Handler,
		},
		{
			MethodName: "subscribe",
			Handler:    _PostofficeService_Subscribe_Handler,
		},
		{
			MethodName: "unsubscribe",
			Handler:    _PostofficeService_Unsubscribe_Handler,
		},
		{
			MethodName: "publish",
			Handler:    _PostofficeService_Publish_Handler,
		},
		{
			MethodName: "disconnect",
			Handler:    _PostofficeService_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "hashRing",
			Handler:       _PostofficeService_HashRing_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "keyRing",
			Handler:       _PostofficeService_KeyRing_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "list",
			Handler:       _PostofficeService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "receive",
			Handler:       _PostofficeService_Receive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "postoffice_service.proto",
}
