// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: repository_object.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepositoryObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryObject) Reset() {
	*x = RepositoryObject{}
	mi := &file_repository_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryObject) ProtoMessage() {}

func (x *RepositoryObject) ProtoReflect() protoreflect.Message {
	mi := &file_repository_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryObject.ProtoReflect.Descriptor instead.
func (*RepositoryObject) Descriptor() ([]byte, []int) {
	return file_repository_object_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryObject) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *RepositoryObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepositoryObject) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RepositoryObject) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

var File_repository_object_proto protoreflect.FileDescriptor

const file_repository_object_proto_rawDesc = "" +
	"\n" +
	"\x17repository_object.proto\x12\bprotocol\"h\n" +
	"\x10RepositoryObject\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branchBX\n" +
	"\x17com.icodesoftware.protoB\x17RepositoryObjectFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_repository_object_proto_rawDescOnce sync.Once
	file_repository_object_proto_rawDescData []byte
)

func file_repository_object_proto_rawDescGZIP() []byte {
	file_repository_object_proto_rawDescOnce.Do(func() {
		file_repository_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_object_proto_rawDesc), len(file_repository_object_proto_rawDesc)))
	})
	return file_repository_object_proto_rawDescData
}

var file_repository_object_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_repository_object_proto_goTypes = []any{
	(*RepositoryObject)(nil), // 0: protocol.RepositoryObject
}
var file_repository_object_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_repository_object_proto_init() }
func file_repository_object_proto_init() {
	if File_repository_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_object_proto_rawDesc), len(file_repository_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repository_object_proto_goTypes,
		DependencyIndexes: file_repository_object_proto_depIdxs,
		MessageInfos:      file_repository_object_proto_msgTypes,
	}.Build()
	File_repository_object_proto = out.File
	file_repository_object_proto_goTypes = nil
	file_repository_object_proto_depIdxs = nil
}
