// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opt           uint32                 `protobuf:"fixed32,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Prefix        uint32                 `protobuf:"fixed32,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Query         *Query                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Context       string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetOpt() uint32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *Request) GetPrefix() uint32 {
	if x != nil {
		return x.Prefix
	}
	return 0
}

func (x *Request) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Request) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Request) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

var File_request_proto protoreflect.FileDescriptor

const file_request_proto_rawDesc = "" +
	"\n" +
	"\rrequest.proto\x12\bprotocol\x1a\n" +
	"data.proto\x1a\vquery.proto\"\x98\x01\n" +
	"\aRequest\x12\x10\n" +
	"\x03opt\x18\x01 \x01(\aR\x03opt\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\aR\x06prefix\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.protocol.DataR\x04data\x12%\n" +
	"\x05query\x18\x04 \x01(\v2\x0f.protocol.QueryR\x05query\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontextBO\n" +
	"\x17com.icodesoftware.protoB\x0eRequestFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_request_proto_rawDescOnce sync.Once
	file_request_proto_rawDescData []byte
)

func file_request_proto_rawDescGZIP() []byte {
	file_request_proto_rawDescOnce.Do(func() {
		file_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)))
	})
	return file_request_proto_rawDescData
}

var file_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_proto_goTypes = []any{
	(*Request)(nil), // 0: protocol.Request
	(*Data)(nil),    // 1: protocol.Data
	(*Query)(nil),   // 2: protocol.Query
}
var file_request_proto_depIdxs = []int32{
	1, // 0: protocol.Request.data:type_name -> protocol.Data
	2, // 1: protocol.Request.query:type_name -> protocol.Query
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_request_proto_init() }
func file_request_proto_init() {
	if File_request_proto != nil {
		return
	}
	file_data_proto_init()
	file_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_proto_goTypes,
		DependencyIndexes: file_request_proto_depIdxs,
		MessageInfos:      file_request_proto_msgTypes,
	}.Build()
	File_request_proto = out.File
	file_request_proto_goTypes = nil
	file_request_proto_depIdxs = nil
}
