// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: request_event.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Duration      uint64                 `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Code          uint32                 `protobuf:"fixed32,6,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEvent) Reset() {
	*x = RequestEvent{}
	mi := &file_request_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEvent) ProtoMessage() {}

func (x *RequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_request_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEvent.ProtoReflect.Descriptor instead.
func (*RequestEvent) Descriptor() ([]byte, []int) {
	return file_request_event_proto_rawDescGZIP(), []int{0}
}

func (x *RequestEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestEvent) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RequestEvent) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *RequestEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RequestEvent) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_request_event_proto protoreflect.FileDescriptor

const file_request_event_proto_rawDesc = "" +
	"\n" +
	"\x13request_event.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\fRequestEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x06R\bduration\x126\n" +
	"\bdateTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04code\x18\x06 \x01(\aR\x04codeBT\n" +
	"\x17com.icodesoftware.protoB\x13RequestEventFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_request_event_proto_rawDescOnce sync.Once
	file_request_event_proto_rawDescData []byte
)

func file_request_event_proto_rawDescGZIP() []byte {
	file_request_event_proto_rawDescOnce.Do(func() {
		file_request_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_event_proto_rawDesc), len(file_request_event_proto_rawDesc)))
	})
	return file_request_event_proto_rawDescData
}

var file_request_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_event_proto_goTypes = []any{
	(*RequestEvent)(nil),          // 0: protocol.RequestEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_request_event_proto_depIdxs = []int32{
	1, // 0: protocol.RequestEvent.dateTime:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_event_proto_init() }
func file_request_event_proto_init() {
	if File_request_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_event_proto_rawDesc), len(file_request_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_event_proto_goTypes,
		DependencyIndexes: file_request_event_proto_depIdxs,
		MessageInfos:      file_request_event_proto_msgTypes,
	}.Build()
	File_request_event_proto = out.File
	file_request_event_proto_goTypes = nil
	file_request_event_proto_depIdxs = nil
}
