// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: response.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Code          uint32                 `protobuf:"fixed32,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *DataSet               `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Task          *Task                  `protobuf:"bytes,5,opt,name=task,proto3" json:"task,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	Nodes         []*HashNode            `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,8,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// used for http response json
	Messages      []*anypb.Any `protobuf:"bytes,9,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *Response) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() *DataSet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Response) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Response) GetNodes() []*HashNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Response) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Response) GetMessages() []*anypb.Any {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_response_proto protoreflect.FileDescriptor

const file_response_proto_rawDesc = "" +
	"\n" +
	"\x0eresponse.proto\x12\bprotocol\x1a\x19google/protobuf/any.proto\x1a\x0edata_set.proto\x1a\n" +
	"task.proto\x1a\n" +
	"meta.proto\x1a\x0fhash_node.proto\x1a\x12subscription.proto\"\xe1\x02\n" +
	"\bResponse\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful\x12\x12\n" +
	"\x04code\x18\x02 \x01(\aR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x04data\x18\x04 \x01(\v2\x11.protocol.DataSetR\x04data\x12\"\n" +
	"\x04task\x18\x05 \x01(\v2\x0e.protocol.TaskR\x04task\x12\"\n" +
	"\x04meta\x18\x06 \x01(\v2\x0e.protocol.MetaR\x04meta\x12(\n" +
	"\x05nodes\x18\a \x03(\v2\x12.protocol.HashNodeR\x05nodes\x12<\n" +
	"\rsubscriptions\x18\b \x03(\v2\x16.protocol.SubscriptionR\rsubscriptions\x120\n" +
	"\bmessages\x18\t \x03(\v2\x14.google.protobuf.AnyR\bmessagesBP\n" +
	"\x17com.icodesoftware.protoB\x0fResponseFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_response_proto_rawDescOnce sync.Once
	file_response_proto_rawDescData []byte
)

func file_response_proto_rawDescGZIP() []byte {
	file_response_proto_rawDescOnce.Do(func() {
		file_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)))
	})
	return file_response_proto_rawDescData
}

var file_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_proto_goTypes = []any{
	(*Response)(nil),     // 0: protocol.Response
	(*DataSet)(nil),      // 1: protocol.DataSet
	(*Task)(nil),         // 2: protocol.Task
	(*Meta)(nil),         // 3: protocol.Meta
	(*HashNode)(nil),     // 4: protocol.HashNode
	(*Subscription)(nil), // 5: protocol.Subscription
	(*anypb.Any)(nil),    // 6: google.protobuf.Any
}
var file_response_proto_depIdxs = []int32{
	1, // 0: protocol.Response.data:type_name -> protocol.DataSet
	2, // 1: protocol.Response.task:type_name -> protocol.Task
	3, // 2: protocol.Response.meta:type_name -> protocol.Meta
	4, // 3: protocol.Response.nodes:type_name -> protocol.HashNode
	5, // 4: protocol.Response.subscriptions:type_name -> protocol.Subscription
	6, // 5: protocol.Response.messages:type_name -> google.protobuf.Any
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_response_proto_init() }
func file_response_proto_init() {
	if File_response_proto != nil {
		return
	}
	file_data_set_proto_init()
	file_task_proto_init()
	file_meta_proto_init()
	file_hash_node_proto_init()
	file_subscription_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_proto_goTypes,
		DependencyIndexes: file_response_proto_depIdxs,
		MessageInfos:      file_response_proto_msgTypes,
	}.Build()
	File_response_proto = out.File
	file_response_proto_goTypes = nil
	file_response_proto_depIdxs = nil
}
