// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: sql_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SqlAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlAccess) Reset() {
	*x = SqlAccess{}
	mi := &file_sql_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlAccess) ProtoMessage() {}

func (x *SqlAccess) ProtoReflect() protoreflect.Message {
	mi := &file_sql_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlAccess.ProtoReflect.Descriptor instead.
func (*SqlAccess) Descriptor() ([]byte, []int) {
	return file_sql_access_proto_rawDescGZIP(), []int{0}
}

func (x *SqlAccess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SqlAccess) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SqlAccess) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_sql_access_proto protoreflect.FileDescriptor

const file_sql_access_proto_rawDesc = "" +
	"\n" +
	"\x10sql_access.proto\x12\bprotocol\"O\n" +
	"\tSqlAccess\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04hostBQ\n" +
	"\x17com.icodesoftware.protoB\x10SqlAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_sql_access_proto_rawDescOnce sync.Once
	file_sql_access_proto_rawDescData []byte
)

func file_sql_access_proto_rawDescGZIP() []byte {
	file_sql_access_proto_rawDescOnce.Do(func() {
		file_sql_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sql_access_proto_rawDesc), len(file_sql_access_proto_rawDesc)))
	})
	return file_sql_access_proto_rawDescData
}

var file_sql_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sql_access_proto_goTypes = []any{
	(*SqlAccess)(nil), // 0: protocol.SqlAccess
}
var file_sql_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sql_access_proto_init() }
func file_sql_access_proto_init() {
	if File_sql_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sql_access_proto_rawDesc), len(file_sql_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sql_access_proto_goTypes,
		DependencyIndexes: file_sql_access_proto_depIdxs,
		MessageInfos:      file_sql_access_proto_msgTypes,
	}.Build()
	File_sql_access_proto = out.File
	file_sql_access_proto_goTypes = nil
	file_sql_access_proto_depIdxs = nil
}
