// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: task_event.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Validator     *JobEvent              `protobuf:"bytes,5,opt,name=validator,proto3" json:"validator,omitempty"`
	Job           *JobEvent              `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_task_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_task_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_task_event_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEvent) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TaskEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskEvent) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TaskEvent) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *TaskEvent) GetValidator() *JobEvent {
	if x != nil {
		return x.Validator
	}
	return nil
}

func (x *TaskEvent) GetJob() *JobEvent {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_task_event_proto protoreflect.FileDescriptor

const file_task_event_proto_rawDesc = "" +
	"\n" +
	"\x10task_event.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"meta.proto\x1a\x0fjob_event.proto\"\x89\x02\n" +
	"\tTaskEvent\x12\"\n" +
	"\x04meta\x18\x01 \x01(\v2\x0e.protocol.MetaR\x04meta\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x120\n" +
	"\tvalidator\x18\x05 \x01(\v2\x12.protocol.JobEventR\tvalidator\x12$\n" +
	"\x03job\x18\x06 \x01(\v2\x12.protocol.JobEventR\x03jobBQ\n" +
	"\x17com.icodesoftware.protoB\x10TaskEventFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_task_event_proto_rawDescOnce sync.Once
	file_task_event_proto_rawDescData []byte
)

func file_task_event_proto_rawDescGZIP() []byte {
	file_task_event_proto_rawDescOnce.Do(func() {
		file_task_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_event_proto_rawDesc), len(file_task_event_proto_rawDesc)))
	})
	return file_task_event_proto_rawDescData
}

var file_task_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_task_event_proto_goTypes = []any{
	(*TaskEvent)(nil),             // 0: protocol.TaskEvent
	(*Meta)(nil),                  // 1: protocol.Meta
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*JobEvent)(nil),              // 3: protocol.JobEvent
}
var file_task_event_proto_depIdxs = []int32{
	1, // 0: protocol.TaskEvent.meta:type_name -> protocol.Meta
	2, // 1: protocol.TaskEvent.start:type_name -> google.protobuf.Timestamp
	2, // 2: protocol.TaskEvent.end:type_name -> google.protobuf.Timestamp
	3, // 3: protocol.TaskEvent.validator:type_name -> protocol.JobEvent
	3, // 4: protocol.TaskEvent.job:type_name -> protocol.JobEvent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_task_event_proto_init() }
func file_task_event_proto_init() {
	if File_task_event_proto != nil {
		return
	}
	file_meta_proto_init()
	file_job_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_event_proto_rawDesc), len(file_task_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_event_proto_goTypes,
		DependencyIndexes: file_task_event_proto_depIdxs,
		MessageInfos:      file_task_event_proto_msgTypes,
	}.Build()
	File_task_event_proto = out.File
	file_task_event_proto_goTypes = nil
	file_task_event_proto_depIdxs = nil
}
