// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: transaction_service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_transaction_service_proto protoreflect.FileDescriptor

const file_transaction_service_proto_rawDesc = "" +
	"\n" +
	"\x19transaction_service.proto\x12\bprotocol\x1a\x0eresponse.proto\x1a\x11transaction.proto\x1a\n" +
	"meta.proto\x1a\n" +
	"task.proto2\xc8\x02\n" +
	"\x12TransactionService\x12-\n" +
	"\x05setup\x12\x0e.protocol.Task\x1a\x12.protocol.Response\"\x00\x129\n" +
	"\n" +
	"askReserve\x12\x15.protocol.Transaction\x1a\x12.protocol.Response\"\x00\x121\n" +
	"\taskFinish\x12\x0e.protocol.Meta\x1a\x12.protocol.Response\"\x00\x121\n" +
	"\tconfirmed\x12\x0e.protocol.Meta\x1a\x12.protocol.Response\"\x00\x120\n" +
	"\bcanceled\x12\x0e.protocol.Meta\x1a\x12.protocol.Response\"\x00\x120\n" +
	"\bfinished\x12\x0e.protocol.Meta\x1a\x12.protocol.Response\"\x00BZ\n" +
	"\x17com.icodesoftware.protoB\x19TransactionServiceFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var file_transaction_service_proto_goTypes = []any{
	(*Task)(nil),        // 0: protocol.Task
	(*Transaction)(nil), // 1: protocol.Transaction
	(*Meta)(nil),        // 2: protocol.Meta
	(*Response)(nil),    // 3: protocol.Response
}
var file_transaction_service_proto_depIdxs = []int32{
	0, // 0: protocol.TransactionService.setup:input_type -> protocol.Task
	1, // 1: protocol.TransactionService.askReserve:input_type -> protocol.Transaction
	2, // 2: protocol.TransactionService.askFinish:input_type -> protocol.Meta
	2, // 3: protocol.TransactionService.confirmed:input_type -> protocol.Meta
	2, // 4: protocol.TransactionService.canceled:input_type -> protocol.Meta
	2, // 5: protocol.TransactionService.finished:input_type -> protocol.Meta
	3, // 6: protocol.TransactionService.setup:output_type -> protocol.Response
	3, // 7: protocol.TransactionService.askReserve:output_type -> protocol.Response
	3, // 8: protocol.TransactionService.askFinish:output_type -> protocol.Response
	3, // 9: protocol.TransactionService.confirmed:output_type -> protocol.Response
	3, // 10: protocol.TransactionService.canceled:output_type -> protocol.Response
	3, // 11: protocol.TransactionService.finished:output_type -> protocol.Response
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_service_proto_init() }
func file_transaction_service_proto_init() {
	if File_transaction_service_proto != nil {
		return
	}
	file_response_proto_init()
	file_transaction_proto_init()
	file_meta_proto_init()
	file_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_service_proto_rawDesc), len(file_transaction_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_service_proto_goTypes,
		DependencyIndexes: file_transaction_service_proto_depIdxs,
	}.Build()
	File_transaction_service_proto = out.File
	file_transaction_service_proto_goTypes = nil
	file_transaction_service_proto_depIdxs = nil
}
