// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: transaction_service.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_Setup_FullMethodName      = "/protocol.TransactionService/setup"
	TransactionService_AskReserve_FullMethodName = "/protocol.TransactionService/askReserve"
	TransactionService_AskFinish_FullMethodName  = "/protocol.TransactionService/askFinish"
	TransactionService_Confirmed_FullMethodName  = "/protocol.TransactionService/confirmed"
	TransactionService_Canceled_FullMethodName   = "/protocol.TransactionService/canceled"
	TransactionService_Finished_FullMethodName   = "/protocol.TransactionService/finished"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	// micro transaction API
	Setup(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error)
	AskReserve(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error)
	AskFinish(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error)
	Confirmed(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error)
	Canceled(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error)
	Finished(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) Setup(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TransactionService_Setup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) AskReserve(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TransactionService_AskReserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) AskFinish(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TransactionService_AskFinish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) Confirmed(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TransactionService_Confirmed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) Canceled(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TransactionService_Canceled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) Finished(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TransactionService_Finished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	// micro transaction API
	Setup(context.Context, *Task) (*Response, error)
	AskReserve(context.Context, *Transaction) (*Response, error)
	AskFinish(context.Context, *Meta) (*Response, error)
	Confirmed(context.Context, *Meta) (*Response, error)
	Canceled(context.Context, *Meta) (*Response, error)
	Finished(context.Context, *Meta) (*Response, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) Setup(context.Context, *Task) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Setup not implemented")
}
func (UnimplementedTransactionServiceServer) AskReserve(context.Context, *Transaction) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AskReserve not implemented")
}
func (UnimplementedTransactionServiceServer) AskFinish(context.Context, *Meta) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AskFinish not implemented")
}
func (UnimplementedTransactionServiceServer) Confirmed(context.Context, *Meta) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirmed not implemented")
}
func (UnimplementedTransactionServiceServer) Canceled(context.Context, *Meta) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Canceled not implemented")
}
func (UnimplementedTransactionServiceServer) Finished(context.Context, *Meta) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Finished not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Setup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Setup(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_AskReserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).AskReserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_AskReserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).AskReserve(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_AskFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).AskFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_AskFinish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).AskFinish(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_Confirmed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Confirmed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Confirmed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Confirmed(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_Canceled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Canceled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Canceled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Canceled(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_Finished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Finished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Finished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Finished(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setup",
			Handler:    _TransactionService_Setup_Handler,
		},
		{
			MethodName: "askReserve",
			Handler:    _TransactionService_AskReserve_Handler,
		},
		{
			MethodName: "askFinish",
			Handler:    _TransactionService_AskFinish_Handler,
		},
		{
			MethodName: "confirmed",
			Handler:    _TransactionService_Confirmed_Handler,
		},
		{
			MethodName: "canceled",
			Handler:    _TransactionService_Canceled_Handler,
		},
		{
			MethodName: "finished",
			Handler:    _TransactionService_Finished_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction_service.proto",
}
