// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: transaction.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Object        *KeyValue              `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Message       *anypb.Any             `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Transaction) GetObject() *KeyValue {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Transaction) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\bprotocol\x1a\x19google/protobuf/any.proto\x1a\x0fkey_value.proto\x1a\n" +
	"meta.proto\x1a\n" +
	"data.proto\"\xb1\x01\n" +
	"\vTransaction\x12\"\n" +
	"\x04meta\x18\x01 \x01(\v2\x0e.protocol.MetaR\x04meta\x12*\n" +
	"\x06object\x18\x02 \x01(\v2\x12.protocol.KeyValueR\x06object\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.protocol.DataR\x04data\x12.\n" +
	"\amessage\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\amessageBS\n" +
	"\x17com.icodesoftware.protoB\x12TransactionFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_proto_goTypes = []any{
	(*Transaction)(nil), // 0: protocol.Transaction
	(*Meta)(nil),        // 1: protocol.Meta
	(*KeyValue)(nil),    // 2: protocol.KeyValue
	(*Data)(nil),        // 3: protocol.Data
	(*anypb.Any)(nil),   // 4: google.protobuf.Any
}
var file_transaction_proto_depIdxs = []int32{
	1, // 0: protocol.Transaction.meta:type_name -> protocol.Meta
	2, // 1: protocol.Transaction.object:type_name -> protocol.KeyValue
	3, // 2: protocol.Transaction.data:type_name -> protocol.Data
	4, // 3: protocol.Transaction.message:type_name -> google.protobuf.Any
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_key_value_proto_init()
	file_meta_proto_init()
	file_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
